language: python

env:
  - TOXENV=pep8
  - TOXENV=py3pep8
  - TOXENV=docs
  - TOXENV=packaging
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=py27 VENDOR=no
  - TOXENV=py34 VENDOR=no
  - TOXENV=py27 VENDOR=no WHEELS=yes
  - TOXENV=py34 VENDOR=no WHEELS=yes

install: .travis/install.sh

script: .travis/run.sh

notifications:
  irc:
    channels:
      # This is set to a secure variable to prevent forks from notifiying the
      # IRC channel whenever they fail a build. This can be removed when travis
      # implements https://github.com/travis-ci/travis-ci/issues/1094.
      # The actual value here is: irc.freenode.org#pypa-dev
      - secure: "zAlwcmrDThlRsZz7CPDGpj4ABTzf7bc/zQXYtvIuqmSj0yJMAwsO5Vx/+qdTGYBvmW/oHw2s/uUgtkZzntSQiVQToKMag2fs0d3wV5bLJQUE2Si2jnH2JOQo3JZWSo9HOqL6WYmlKGI8lH9FVTdVLgpeJmIpLy1bN4zx4/TiJjc="
    use_notice: true
    skip_join: true
